/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AddressSuggestionDto {
  field: AddressSuggestionDto.FieldEnum;
  street: string | null;
  city: string | null;
  zip: string | null;
  country: string | null;
}
export namespace AddressSuggestionDto {
  export type FieldEnum = 'country' | 'city' | 'zip' | 'street';
  export const FieldEnum = {
    Country: 'country' as FieldEnum,
    City: 'city' as FieldEnum,
    Zip: 'zip' as FieldEnum,
    Street: 'street' as FieldEnum,
  };
}
