/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ClientSuggestionDto {
  field: ClientSuggestionDto.FieldEnum;
  value: string | null;
}
export namespace ClientSuggestionDto {
  export type FieldEnum =
    | 'clientName'
    | 'address'
    | 'taxNumber'
    | 'registrationNumber'
    | 'email'
    | 'phone'
    | 'contactName'
    | 'contactPosition'
    | 'website';
  export const FieldEnum = {
    ClientName: 'clientName' as FieldEnum,
    Address: 'address' as FieldEnum,
    TaxNumber: 'taxNumber' as FieldEnum,
    RegistrationNumber: 'registrationNumber' as FieldEnum,
    Email: 'email' as FieldEnum,
    Phone: 'phone' as FieldEnum,
    ContactName: 'contactName' as FieldEnum,
    ContactPosition: 'contactPosition' as FieldEnum,
    Website: 'website' as FieldEnum,
  };
}
