/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ClientSuggestionDto {
  field: ClientSuggestionDto.FieldEnum;
  value: string | null;
}
export namespace ClientSuggestionDto {
  export type FieldEnum =
    | 'generalName'
    | 'address'
    | 'generalTaxNumber'
    | 'generalRegistrationNumber'
    | 'contactEmail'
    | 'contactPhone'
    | 'contactName'
    | 'contactPosition'
    | 'website';
  export const FieldEnum = {
    GeneralName: 'generalName' as FieldEnum,
    Address: 'address' as FieldEnum,
    GeneralTaxNumber: 'generalTaxNumber' as FieldEnum,
    GeneralRegistrationNumber: 'generalRegistrationNumber' as FieldEnum,
    ContactEmail: 'contactEmail' as FieldEnum,
    ContactPhone: 'contactPhone' as FieldEnum,
    ContactName: 'contactName' as FieldEnum,
    ContactPosition: 'contactPosition' as FieldEnum,
    Website: 'website' as FieldEnum,
  };
}
