/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ClientAddress {
  type: ClientAddress.TypeEnum;
  city: string;
  zip: string;
  street: string;
  country: string;
}
export namespace ClientAddress {
  export type TypeEnum = 'site' | 'premise';
  export const TypeEnum = {
    Site: 'site' as TypeEnum,
    Premise: 'premise' as TypeEnum,
  };
}
