/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateSoftwarePackage } from './createSoftwarePackage';
import { StatusLessGeneralCustomerAccountInformation } from './statusLessGeneralCustomerAccountInformation';
import { CreateIkontBoxGroup } from './createIkontBoxGroup';
import { CreateHardwareGroup } from './createHardwareGroup';

export interface CustomerDto {
  general: StatusLessGeneralCustomerAccountInformation;
  softwarePackages: Array<CreateSoftwarePackage>;
  hardwareGroups: Array<CreateHardwareGroup>;
  ikontBoxGroups: Array<CreateIkontBoxGroup>;
}
