/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CustomerDetailsSuggestionDto {
  field: CustomerDetailsSuggestionDto.FieldEnum;
  value: string | null;
}
export namespace CustomerDetailsSuggestionDto {
  export type FieldEnum = 'clientName' | 'administratorName';
  export const FieldEnum = {
    ClientName: 'clientName' as FieldEnum,
    AdministratorName: 'administratorName' as FieldEnum,
  };
}
