/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CustomerAccountListColumnVisibility {
  clientName: boolean;
  customerAccountId: boolean;
  adminPerson: boolean;
  email: boolean;
  administratorName: boolean;
  customerAccountState: boolean;
  softwarePackage: boolean;
  storageCapacity: boolean;
  softwareLicenceType: boolean;
  startDate: boolean;
  endDate: boolean;
  registrationState: boolean;
}
