/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FullUserDto {
  id: number;
  userName: string;
  userEmail: string;
  role: Array<string>;
  userState: FullUserDto.UserStateEnum;
  registrationState: FullUserDto.RegistrationStateEnum;
}
export namespace FullUserDto {
  export type UserStateEnum = 'ACTIVE' | 'SUSPENDED';
  export const UserStateEnum = {
    Active: 'ACTIVE' as UserStateEnum,
    Suspended: 'SUSPENDED' as UserStateEnum,
  };
  export type RegistrationStateEnum = 'PENDING' | 'REGISTRATION' | 'DONE';
  export const RegistrationStateEnum = {
    Pending: 'PENDING' as RegistrationStateEnum,
    Registration: 'REGISTRATION' as RegistrationStateEnum,
    Done: 'DONE' as RegistrationStateEnum,
  };
}
