/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface HardwareSuggestionDto {
  field: HardwareSuggestionDto.FieldEnum;
  type: HardwareSuggestionDto.TypeEnum;
  value: string | null;
}
export namespace HardwareSuggestionDto {
  export type FieldEnum = 'id' | 'name';
  export const FieldEnum = {
    Id: 'id' as FieldEnum,
    Name: 'name' as FieldEnum,
  };
  export type TypeEnum = 'box' | 'hardware';
  export const TypeEnum = {
    Box: 'box' as TypeEnum,
    Hardware: 'hardware' as TypeEnum,
  };
}
