/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ManagementInformation {
  administratorName: string;
  customerAccountState: ManagementInformation.CustomerAccountStateEnum;
  registrationState: ManagementInformation.RegistrationStateEnum;
}
export namespace ManagementInformation {
  export type CustomerAccountStateEnum = 'active' | 'suspended';
  export const CustomerAccountStateEnum = {
    Active: 'active' as CustomerAccountStateEnum,
    Suspended: 'suspended' as CustomerAccountStateEnum,
  };
  export type RegistrationStateEnum = 'inProgress' | 'registered' | 'active';
  export const RegistrationStateEnum = {
    InProgress: 'inProgress' as RegistrationStateEnum,
    Registered: 'registered' as RegistrationStateEnum,
    Active: 'active' as RegistrationStateEnum,
  };
}
