/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateIkontBoxGroup } from './updateIkontBoxGroup';
import { UpdateGeneralCustomerAccountInformation } from './updateGeneralCustomerAccountInformation';
import { UpdateSoftwarePackage } from './updateSoftwarePackage';
import { UpdateHardwareGroup } from './updateHardwareGroup';

export interface UpdateCustomerDto {
  id: string;
  general: UpdateGeneralCustomerAccountInformation;
  softwarePackages: Array<UpdateSoftwarePackage>;
  hardwareGroups: Array<UpdateHardwareGroup>;
  ikontBoxGroups: Array<UpdateIkontBoxGroup>;
}
