/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateCustomerDto } from './updateCustomerDto';

export interface UpdateCustomerReqDto {
  customer: UpdateCustomerDto;
  type: UpdateCustomerReqDto.TypeEnum;
}
export namespace UpdateCustomerReqDto {
  export type TypeEnum = 'box' | 'software' | 'hardware' | 'general';
  export const TypeEnum = {
    Box: 'box' as TypeEnum,
    Software: 'software' as TypeEnum,
    Hardware: 'hardware' as TypeEnum,
    General: 'general' as TypeEnum,
  };
}
