/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientListColumnVisibility } from './clientListColumnVisibility';

export interface UserSettingsDtoClientListColumnVisibility {
  generalName: boolean;
  address: boolean;
  generalTaxNumber: boolean;
  generalRegistrationNumber: boolean;
  contactEmail: boolean;
  contactPhone: boolean;
  contactName: boolean;
  generalType: boolean;
  contactPosition: boolean;
  website: boolean;
}
