/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { LoginDto } from '../model/models';
import { LoginResponseDto } from '../model/models';
import { PasswordResetDto } from '../model/models';

import { Configuration } from '../configuration';

export interface AuthenticationServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   */
  authControllerGetUserClaims(
    extraHttpRequestParams?: any
  ): Observable<Array<string>>;

  /**
   *
   *
   * @param loginDto
   */
  authControllerLoginUser(
    loginDto: LoginDto,
    extraHttpRequestParams?: any
  ): Observable<LoginResponseDto>;

  /**
   *
   *
   * @param passwordResetDto
   */
  authControllerResetPassowrd(
    passwordResetDto: PasswordResetDto,
    extraHttpRequestParams?: any
  ): Observable<PasswordResetDto>;
}
