/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { ClientDto } from '../model/models';
import { ClientExistsResponseDto } from '../model/models';
import { ClientListDto } from '../model/models';
import { FullClientDto } from '../model/models';
import { IdRepsponeDto } from '../model/models';
import { IdsRepsponeDto } from '../model/models';
import { PositionDto } from '../model/models';

import { Configuration } from '../configuration';

export interface ClientManagementServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param name
   */
  clientManagementControllerClientExists(
    name: string,
    extraHttpRequestParams?: any
  ): Observable<ClientExistsResponseDto>;

  /**
   *
   *
   * @param clientDto
   */
  clientManagementControllerCreate(
    clientDto: ClientDto,
    extraHttpRequestParams?: any
  ): Observable<FullClientDto>;

  /**
   *
   *
   */
  clientManagementControllerFindAll(
    extraHttpRequestParams?: any
  ): Observable<Array<ClientListDto>>;

  /**
   *
   *
   * @param id
   */
  clientManagementControllerFindOne(
    id: string,
    extraHttpRequestParams?: any
  ): Observable<FullClientDto>;

  /**
   *
   *
   */
  clientManagementControllerFindPositions(
    extraHttpRequestParams?: any
  ): Observable<Array<PositionDto>>;

  /**
   *
   *
   * @param id
   */
  clientManagementControllerRemove(
    id: string,
    extraHttpRequestParams?: any
  ): Observable<IdRepsponeDto>;

  /**
   *
   *
   * @param ids
   */
  clientManagementControllerRemoveManies(
    ids: string,
    extraHttpRequestParams?: any
  ): Observable<IdsRepsponeDto>;

  /**
   *
   *
   * @param fullClientDto
   */
  clientManagementControllerUpdate(
    fullClientDto: FullClientDto,
    extraHttpRequestParams?: any
  ): Observable<FullClientDto>;
}
