/**
 * Ikont Web Api tttt
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { AddressSuggestionDto } from '../model/models';

import { Configuration } from '../configuration';

export interface LocationServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param addressSuggestionDto
   */
  locationControllerGetAddressSuggestion(
    addressSuggestionDto: AddressSuggestionDto,
    extraHttpRequestParams?: any
  ): Observable<Array<string>>;
}
